# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WJB667p6H_gzG77SALCa4_8CFYy48mIV
"""

import streamlit as st
import joblib
import pandas as pd

model = joblib.load("laptop_price_model.pkl")

st.title("💻 Laptop Price Predictor")

company = st.selectbox(
    "Brand",
    ["Apple", "HP", "Lenovo", "Dell", "Asus", "Acer", "MSI", "Toshiba", "Samsung", "Other"]
)

type_name = st.selectbox(
    "Laptop Type",
    ["Ultrabook", "Notebook", "Gaming", "2 in 1 Convertible", "Workstation", "Netbook"]
)

inches = st.number_input(
    "Screen Size (inches)",
    min_value=10.0,
    max_value=18.0,
    value=15.6
)

cpu_company = st.selectbox(
    "CPU Company",
    ["Intel", "AMD", "Samsung"]
)

cpu_type = st.text_input(
    "CPU Type",
    "Core i5"
)

cpu_frequency = st.number_input(
    "CPU Frequency (GHz)",
    min_value=0.5,
    max_value=5.0,
    value=2.5
)

ram = st.selectbox(
    "RAM (GB)",
    [2, 4, 6, 8, 12, 16, 24, 32, 64]
)

memory = st.text_input(
    "Storage",
    "512GB SSD"
)

gpu_company = st.selectbox(
    "GPU Company",
    ["Intel", "Nvidia", "AMD", "ARM"]
)

gpu_type = st.text_input(
    "GPU Type",
    "HD Graphics"
)

opsys = st.selectbox(
    "Operating System",
    ["Windows 10", "Windows 7", "macOS", "No OS", "Linux", "Chrome OS"]
)

weight = st.number_input(
    "Weight (kg)",
    min_value=0.5,
    max_value=5.0,
    value=2.0
)

if st.button("💰 Predict Price"):

    laptop = pd.DataFrame([{
        "Company": company,
        "TypeName": type_name,
        "Inches": inches,
        "CPU_Company": cpu_company,
        "CPU_Type": cpu_type,
        "CPU_Frequency (GHz)": cpu_frequency,
        "RAM (GB)": ram,
        "Memory": memory,
        "GPU_Company": gpu_company,
        "GPU_Type": gpu_type,
        "OpSys": opsys,
        "Weight (kg)": weight
    }])

    prediction = model.predict(laptop)

    price_euro = prediction[0]
    price_egp = price_euro * 58

    st.success(f"💰 Estimated Price: €{price_euro:,.0f}")
    st.info(f"🇪🇬 Estimated Price: {price_egp:,.0f} EGP")